# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  # Definimos una IP privada fija para acceder a ella fácilmente
  config.vm.network "private_network", ip: "192.168.56.8" 
end