server {
    listen 80;
    server_name mario.test;
    root /usr/share/nginx/html;
    index index.html;

    # 1. La raíz es pública 
    location / {
        try_files $uri $uri/ =404;
    }

    # 2. Solo contact.html pide contraseña 
    location /contact.html {
        auth_basic "Area Privada de Luna";
        auth_basic_user_file /etc/nginx/.htpasswd;
    }
}