server {
    listen 80;
    listen [::]:80;
    server_name mario.test; 

    # Carpeta donde están mis html DENTRO del contenedor
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Configuración para proteger toda la web
    location / {
        auth_basic "Area restringida de Mario Luna"; 
        auth_basic_user_file /etc/nginx/.htpasswd; 

        try_files $uri $uri/ =404;
    }
}

